"""Initial migration

Revision ID: b56e84f68468
Revises: 
Create Date: 2024-09-05 20:00:23.757472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'b56e84f68468'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tema_texto', sa.Text(), nullable=False),
    sa.Column('pregunta_id', sa.String(), nullable=False),
    sa.Column('pregunta_fecha_creacion', sa.String(), nullable=False),
    sa.Column('pregunta_texto', sa.Text(), nullable=False),
    sa.Column('respuesta_fecha_actualizacion', sa.String(), nullable=False),
    sa.Column('respuesta_texto', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_relacionadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuesta_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tema_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tema_links')
    op.drop_table('respuesta_links')
    op.drop_table('preguntas_relacionadas')
    op.drop_table('documents')
    # ### end Alembic commands ###
